### ISSUE TITLE
Contributors link on website leads to 404

### ISSUE THREAD

**Issue by Austinate** [tuist/website#14]
Hi there!

## Context 🕵️‍♀️
Trying to open [Tuist org. contributors](https://github.com/orgs/tuist/teams/contributors) url from header.
<img width="965" alt="screen shot 2018-10-08 at 17 23 18" src="https://user-images.githubusercontent.com/4790464/46614578-de125180-cb1e-11e8-9678-86b3054114b7.png">

## What 🌱
We get 404 at this url. Looks like this page is available only to contributors themselves.
<img width="713" alt="image" src="https://user-images.githubusercontent.com/4790464/46614681-23cf1a00-cb1f-11e8-8231-0f046ed1f0bb.png">

There are 0 people shown in team organization right now
<img width="755" alt="screen shot 2018-10-08 at 17 20 05" src="https://user-images.githubusercontent.com/4790464/46614876-9809bd80-cb1f-11e8-9f59-5490969dbb91.png">

## Proposal 🎉

First and immediate suggestion would be to use [Tuist contributors repo url](https://github.com/tuist/tuist/graphs/contributors).
But i think it's not the best way to solve since it'll show contributors only from 1 repo.

Maybe it can be enough, or we can create another webpage which will have list of urls for contributors of each repo (Nor sure if it's needed though since we already have url to organization in header from which everything is easily discoverable).

What do you think?

**Comment by pepibumur** [comment]
Thanks for reporting this @Austinate and nice catch. I think we can redirect to [this page](https://github.com/orgs/tuist/people) where all the developers that belong to the organization are listed. What do you think?

**Comment by Austinate** [comment]
@pepibumur I think it's a good idea, however right now it shows 0 people in organization, is this intended? 
![image](https://user-images.githubusercontent.com/4790464/47744357-d2cbc500-dc89-11e8-8aa3-4c18a960cc38.png)

**Comment by pepibumur** [comment]
Ouch, that's weird. Maybe the list of contributors doesn't show up unless you are part of the organization. What do you think about this?

1. Extract [this piece of HTML](https://github.com/tuist/website/blob/master/index.html#L174) into an include, `_contributors.html`.
2. Create a new page, `contributors.md` that includes that HTML.
3. Update the link to open that page.

If you could open a PR with those changes that'd be great @Austinate

**Comment by Austinate** [comment]
I've tested and what i can see so far: after joining an organization it's up to specific user to set own profile as public/private in terms of organization:
